const colors = {
  light: {
    text: '#FFFFFF',
    tint: '#3D5AFE',
    background: '#0B1026',
    foreground: '#FFFFFF',
    card: '#141D3A',
    cardForeground: '#FFFFFF',
    primary: '#3D5AFE',
    primaryForeground: '#FFFFFF',
    secondary: '#00BCD4',
    secondaryForeground: '#FFFFFF',
    muted: '#1A2A5C',
    mutedForeground: '#8892B0',
    accent: '#2ECC71',
    accentForeground: '#FFFFFF',
    destructive: '#FF5370',
    destructiveForeground: '#FFFFFF',
    border: 'rgba(255,255,255,0.08)',
    input: '#1A2A5C',
    warning: '#F59E0B',
    gold: '#F6C90E',
  },
  dark: {
    text: '#FFFFFF',
    tint: '#3D5AFE',
    background: '#0B1026',
    foreground: '#FFFFFF',
    card: '#141D3A',
    cardForeground: '#FFFFFF',
    primary: '#3D5AFE',
    primaryForeground: '#FFFFFF',
    secondary: '#00BCD4',
    secondaryForeground: '#FFFFFF',
    muted: '#1A2A5C',
    mutedForeground: '#8892B0',
    accent: '#2ECC71',
    accentForeground: '#FFFFFF',
    destructive: '#FF5370',
    destructiveForeground: '#FFFFFF',
    border: 'rgba(255,255,255,0.08)',
    input: '#1A2A5C',
    warning: '#F59E0B',
    gold: '#F6C90E',
  },
  radius: 16,
};

export default colors;
